### ISSUE TITLE
Use GITHUB_TOKEN by default

### ISSUE THREAD

**Issue by alexpovel** [extractions/setup-just#10]
Thanks for putting together this action!

I recently set up `just` and am now running it in a pipeline with a matrix of 3 different Python versions on 3 different OSes, resulting in 9 parallel jobs. See [this run](https://github.com/alexpovel/betterletter/actions/runs/4009490548) for context. It failed on its first try using `just` and `setup-just`!

In the README, it says:

https://github.com/extractions/setup-just/blob/95b912dc5d3ed106a72907f2f9b91e76d60bdb76/README.md#L27-L29

I'd argue my use case is not that rare. After all, unauthenticated API access is [limited to just 60 requests](https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#checking-your-rate-limit-status) per hour. It seems this action exhausts these quickly, which is fair and can happen.

One suggestion: some actions use the `GITHUB_TOKEN` *by default*, e.g. [`release-please`](https://github.com/google-github-actions/release-please-action). Would it be possible to implement this behaviour? It would save users from having to specify the environment variable manually, and would eradicate nasty surprises like the one above almost entirely (5000 requests per hour limit).

**Comment by simse** [comment]
Happy to submit a PR for this, @rossmacarthur. I've seen this error on almost every actions run now, so I'd argue it's not particularly rare.

**Comment by rossmacarthur** [comment]
@simse Happy to accept a PR for this.

**Comment by simse** [comment]
PR fixing this is merged in. Time to close this issue 😄

**Comment by rossmacarthur** [comment]
Fixed in #11
