### ISSUE TITLE
Document how to bundle the action

### ISSUE THREAD

**Issue by soenkehahn** [extractions/setup-just#3]
I think it'd be good to have a documented way to rebuild the minified bundle in `dist`. Ideally in a reproducible way.

I tried to figure out how to do that, here's what I did:
- I looked at `package.json` and it seems like the `dist` directory can be populated by `npm run-script build`. (Is that correct?)
- I tried that, but `ncc` couldn't be found. There's multiple `ncc`s on npm, is [this](https://www.npmjs.com/package/@vercel/ncc) the one being used here? If yes, I think it should be added to the dev dependencies. IIRC all executables from dev dependencies are automatically available through the `$PATH` when running `npm run-script something`.
- After adding `@vercel/ncc` to the dev dependencies I get other errors, e.g. `TS2792: Cannot find module '@extractions/setup-crate'. Did you mean to set the 'moduleResolution' option to 'node', or to add aliases to the 'paths' option?`.

**Comment by rossmacarthur** [comment]
Hi @soenkehahn,  this should be resolved by 5675d4c:

- I have added `@vercel/ncc` to the dev dependencies.
- I also added a new development section to the README.
- This error `Did you mean to set the 'moduleResolution' option to 'node', or to add aliases to the 'paths' option?.` should no longer happen.

You should be able to regenerate the `dist/` directory after doing the following:

```
npm i
npm run build
```
