### ISSUE TITLE
Deprecated Node version warnings

### ISSUE THREAD

**Issue by olix0r** [extractions/setup-just#6]
Using this action now triggers a deprecation warning:

> `Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: extractions/setup-just`

**Comment by olix0r** [comment]
Ah, this was fixed by 1.5.0. Dependabot doesn't automatically pick this release up since there isn't a new tag for this version.

**Comment by bruceadams** [comment]
How do I use 1.5.0?

```yaml
  - name: Setup just
    uses: extractions/setup-just@v1.5.0
```

gives me this error

```
Error: Unable to resolve action `extractions/setup-just@v1.5.0`, unable to find version `v1.5.0`
```

**Comment by olix0r** [comment]
I'm using the full SHA

```yaml
- uses: extractions/setup-just@aa5d15c144db4585980a44ebfdd2cf337c4f14cb
```

**Comment by kevinmatthes** [comment]
It seems as if the latest version shall be used as in the following.

```yaml
- uses: extractions/setup-just@v1
```

When taking a look at the releases, there is no release for v1.5.0 but for all other older versions.  Instead, there is a release v1 marked as the latest.  Obviously, the maintainer updates v1 to the respective latest version whenever they release a new one.  This procedure is also practiced in the repository of the `checkout` Action where, however, also an additional release is published such that for the latest version, there are always two releases.

@bruceadams, did this information help you?

**Comment by bruceadams** [comment]
Ah. I was confused (well, I still am confused, just a little less so).

Using `extractions/setup-just@v1`, GitHub Actions tells me this:

```
Download action repository 'extractions/setup-just@v1' (SHA:95b912dc5d3ed106a72907f2f9b91e76d60bdb76)
```

https://github.com/extractions/setup-just/commit/95b912dc5d3ed106a72907f2f9b91e76d60bdb76 is 1.5.0 🎉.

(I do not know where the deprecated warnings I'm getting from my workflow are coming from, but it's not from this.)

**Comment by kevinmatthes** [comment]
I just submitted a feature request for a second tag for the latest version:  #7.  This should challenge and hopefully also solve the issues discussed here.  If you agree with the idea, please consider to comment and / or react on #7.
