### ISSUE TITLE
[Feature Request] Tag Latest Version Twice

### ISSUE THREAD

**Issue by kevinmatthes** [extractions/setup-just#7]
Hello, @rossmacarthur!

Thank you for this Action!

With this issue, I would like to ask you to give the latest a second tag with its whole version number (`v1.5.0`) in addition to the `v1` tag.  This procedure is practiced, for example, also by the maintainers of the [`checkout`](https://github.com/actions/checkout/tags) Action.

The reason for this request is that, at the moment, the current tagging strategy lead to some confusion, as the discussion in #6 shows.  Always giving the latest version a second tag in addition to moving the `v1` tag forwards would not break anything for users preferring the major tag but benefits automatic version updates by Dependabot and furthermore clarifies the current version number.

Please consider to give the version 1.5.0 a second tag named `v1.5.0`.

**Comment by rossmacarthur** [comment]
Woops, looks like I forgot to do this. Done.
